name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment for deployment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deploying the application... ${{ github.event.inputs.environment }}"
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
